### PR TITLE
Fix 135 "h2 db + local pidsystem may cause unexpected errors"

### LINKED ISSUE #135: H2 DB + LOCAL PidSystem may cause unexpected errors
**Describe the bug**
In the default configuration. H2 is configured as datasource and LOCAL as PIDSystem. Creating a new FDO will cause an instance of `PidDatabaseObject` to be created and written to the configured database. In H2, ElementCollections seems to be stored in a single text column, which has a default size of 256 characters, whereas other DBMS, e.g. Postgres, use a separate table. For H2, this will result in an error (HTTP 409 is returned, which is wrong but currently worked on) if the sum of all characters in the PID record exceeds this limit and the operation is aborted. 

It may help to update the annotation at `entries` to

`@Column(columnDefinition="TEXT", length = 1000)`

but this was not tested, yet. Alternatively, switching to Postgres did help.

### PR DESCRIPTION
**Pull request by Pfeil**
Fix #135 

- [x] Reproduced issue
  - [x] tested records with large amounts of keys and values → issue is reproducible (use clean build, if not)
    - [x] Test cleanup and analysis needed to confirm
  - [ ] ~~tested long values~~ (did not cause the issue)
- [x] Fixed issue
  - [x] Compatibility to other databases: We raised a default value. If this value affects a database now, it affected databases also in beforehand. The change should therefore fully compatible.
- [ ] ~~Catch such errors in future to return better errors via REST~~ → will be done in #125 

---

Other tasks:

- [x] Clean new tests a little, make them more sane and try to include validation if the API tests remain (we are tying to check the DB mainly …)
- [x] check if the tests have too much impact on the CI runtime

### CODE REVIEW

**Comment by Pfeil** [comment]
Tests fail, but I can not see which. There is one test skipped for unknown reasons... maybe this causes a fail. I do not think this helps with the issue, but I'll look into it.

File: src/main/java/edu/kit/datamanager/pit/pidsystem/impl/local/PidDatabaseObject.java [hunk 1]
```diff
@@ -32,7 +32,22 @@ public class PidDatabaseObject {
...
+     * The h2 database we use for testing has a CHARACTER VARYING limit of
+     * 1_000_000_000
+     * (http://h2database.com/html/datatypes.html#character_varying_type).
+     * 
+     * Postgres does not have a limit according to
+     * https://www.postgresql.org/docs/current/datatype-character.html, but we
+     * assume it will not use its text datatype for the collection anyway.
+     */
     @ElementCollection(fetch = FetchType.EAGER)
+    @Column(length = 1_000_000_000)
```
Comment (Pfeil) [inline src/main/java/edu/kit/datamanager/pit/pidsystem/impl/local/PidDatabaseObject.java:50]: This line fixed the issue. Affected were only databases which map the collection to a String (character varying) anyway, so for example it should not affect Postgres at all (because it does not use a string and the length only affects strings in this column).

All other changes are tests or comments.

Comment (ThomasJejkal) [reply src/main/java/edu/kit/datamanager/pit/pidsystem/impl/local/PidDatabaseObject.java:50]: Sure, this should help, but seems like an overkill. ;-) I'm not sure how affected databases deal with such numbers, in the worst case, a lot of memory (> 1 GB) might be reserved for situations, where many entries are in this column. However, such databases should never be used in production anyways, so something smaller could be sufficient including a short note in the configuration file, that there are such limitations.

Something which concerns me more is this one: 

[https://dev.mysql.com/doc/refman/8.0/en/char.html#:~:text=Values%20in%20VARCHAR%20columns%20are,value%20from%200%20to%2065%2C535.](https://dev.mysql.com/doc/refman/8.0/en/char.html#:~:text=Values%20in%20VARCHAR%20columns%20are,value%20from%200%20to%2065%2C535.)

According to that, there might be a limitation of varchar columns for some databases (which are actually not affected) and I'm not sure how they deal with such numbers.

Comment (Pfeil) [reply src/main/java/edu/kit/datamanager/pit/pidsystem/impl/local/PidDatabaseObject.java:50]: - My test needs at least a length of ~6500 (100 attributes with 100 values each, each attribute or value being a PID with maybe a length of ~20).
- > [For MySQL] The length can be specified as a value from 0 to 65,535. (https://dev.mysql.com/doc/refman/8.0/en/char.html) (I do not believe there would be such a ridiculous mapping being done in MySQL)
- > [For SQLite] The default value of this macro is 1 billion (1 thousand million or 1,000,000,000). (https://www.sqlite.org/limits.html#max_length) (Not sure if it would be affected from the weird mapping, but the default is already high here, so actually we would restrict it, if it would be affected)
- Same for h2, but default was 255

My impression is that databases with limited capabilities / data types like h2 tend to have a higher varchar limit for compensation. I'd suggest either 10_000 (6500 + some buffer) or the upper limit of MySQL if the goal is to not make it too large. What do you think?

Comment (ThomasJejkal) [reply src/main/java/edu/kit/datamanager/pit/pidsystem/impl/local/PidDatabaseObject.java:50]: I assume the limits of MySQL to be fine and sufficient. As soon as we are talking about records of this size, we might have performance issues anyways so let's avoid them by technical limitation. ;-)
